"use client";
import Link from "next/link";

/* export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}; */
const routes = [
  { name: "About", href: "/about" },
  { name: "Login", href: "/login" },
  { name: "Register", href: "/register" },
  { name: "Blogs", href: "/blog" },
];

import { usePathname } from "next/navigation";

export default function AuthRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const year: Date = new Date();
  const pathName = usePathname();
  return (
    <html lang="en">
      <body>
        <header
          style={{
            background: "skyblue",
            color: "black",
            padding: "1rem",
            display: "flex",
            gap: "10px",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          {routes.map((route) => {
            const isActive: boolean =
              route.href === pathName ||
              (pathName.startsWith(route.href) && route.href !== "/");
            return (
              <Link
                style={{ color: isActive ? "green" : "blue" }}
                key={route.name}
                href={route.href}
              >
                {route.name}
              </Link>
            );
          })}
          <Link href="/article-1?lang=en">Article 1</Link>
          <Link href="/article-1?lang=fr">Article 1</Link>
          <Link href="/article-1?lang=sp">Article 1</Link>
        </header>
        {children}
        <footer
          style={{ background: "skyblue", color: "black", padding: "1rem" }}
        >
          Footer &copy; {year.getFullYear()}
        </footer>
      </body>
    </html>
  );
}
